server:
  port: 8080 # ??????

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/rehab_manager_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 192.168.88.10
      port: 6379
      database: 0
      password:
      timeout: 10000ms
  sql:
    init:
      mode: never  # ?????????????????

# MyBatis-Plus ??
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ?????? SQL ?????????
    map-underscore-to-camel-case: true # ?????????????? Java ?????

# 自定义 JWT 配置
jwt:
  # 256-bit 随机乱码密钥
  secret: 4Z5c8e2g5j8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWnZr4u7x!A%D*F-J
  # 过期时间（毫秒），这里写的是 7 天
  expire-time: 604800000